### ISSUE TITLE
Rename sign-up algorithm?

### ISSUE THREAD

**Issue by dj2** [w3c-fedid/FedCM#126]
The naming of the `sign-up` algorithm is slightly confusing. Could this be renamed to `sign-up to RP` algorithm to make it clear this is the RP that needs to be signed up, not sign-up to the IDP.

**Comment by cbiesinger** [comment]
(https://fedidcg.github.io/FedCM/#request-permission-to-sign-up is the current version of the mentioned algorithm, I think)

**Comment by samuelgoto** [comment]
This seems to be resolved based on @cbiesinger 's last comment, feel free to reopen if you disagree and we have something that we could act on.

https://w3c-fedid.github.io/FedCM/#request-permission-to-sign-up
