### ISSUE TITLE
Define identity in the spec

### ISSUE THREAD

**Issue by dj2** [w3c-fedid/FedCM#137]
There is no definition of the term `identity` in the spec. Create definition and link as needed.

**Comment by samuelgoto** [comment]
It would be good if this was something that we could reference, as oppose to redefine. I don't know if we'll be able to find something off the shelf, but if we can, that's best.

The OpenID, WebAuthn, OAuth specs are places I'd look at.

**Comment by asr-enid** [comment]
https://openid.net/specs/openid-connect-core-1_0.html#Terminology

Should have most of them

**Comment by npm1** [comment]
This term is not something the spec needs to define, closing
