### ISSUE TITLE
Security Threat Model

### ISSUE THREAD

**Issue by achimschloss** [w3c-fedid/FedCM#28]
Other than functional and privacy related questions, security related aspects of a new Identity API are of paramount importance for IDPs. The IETF and OpenID Foundation have extensive security threat models and best practices documentation for the related core protocols, which are continuously extended. Latest relevant ones seem to be:

- [OAuth 2.0 for Browser-Based Apps](https://tools.ietf.org/html/draft-ietf-oauth-browser-based-apps-06)
- [OAuth 2.0 Security Best Current Practice](https://tools.ietf.org/html/draft-ietf-oauth-security-topics-15)

Given the large majority of IDPs are based on OAuth 2.0/OpenID connect and would need to work with a sort of adapted browser client type, has there been any assessment yet on how WebID would impact the above? Given WebID would quite substantially change the flows that seems to need careful consideration.

**Comment by asr-enid** [comment]
Given WebID was presented at OAuth Security Workshop last week there might be some follow-ups already.

**Comment by samuelgoto** [comment]
@kenrb any thoughts on how to go about this?

**Comment by gffletch** [comment]
I'm definitely interested in feedback from the OAuth Security Workshop as a number of the items in the WebID proposal directly affect OAuth2 based flows. I'm thinking specifically around what this means for JAR, PAR and RAR :)

**Comment by samuelgoto** [comment]
> I'm definitely interested in feedback from the OAuth Security Workshop as a number of the items in the WebID proposal directly affect OAuth2 based flows.

Yep, agreed, authorization is an area that we need to do a much deeper dive ... Here is a shallow exploration:

https://github.com/WICG/WebID/blob/master/design.md#authorization

>  I'm thinking specifically around what this means for JAR, PAR and RAR :)

Can you expand on this a bit more?

**Comment by asr-enid** [comment]
I'm thinking about:

How would WebID allow to authenticate the **RPs Client** for example - with basic browser primitives this is done with PKCE (code_verifier, code_challenge) + other security related mechanism (nonce, state), CORS endpoint protections and callback checks. Authenticating a JS based RP (which cannot securely store client credentials and pass them) requires strict implementations. 

Given WebIDs design would pass ID-Tokens and other sensitive Information via the RP-Side and IDP-Side JS-APIs the question is how the IDP should treat this. Security best practices with OAuth all revolve around basic browser primitives, the question is how the RP and IDP side API would be treated from a security/authentication perspective (for example such that the IDP is able to authenticate an RP as being legitimate).

**Comment by asr-enid** [comment]
> > I'm thinking specifically around what this means for JAR, PAR and RAR :)
> 
> Can you expand on this a bit more?

I guess @gffletch is referring to OAuth Extensions like [PAR](https://tools.ietf.org/id/draft-lodderstedt-oauth-par-00.html) (Pushed Authentication Request) - this is a security extension to protect the IdP from client impersonation in OAuth 2.0, where client_id, redirect_url etc are not observable by the user_agent anymore. 

Client impersonation would be one item for the security model for example -  https://github.com/WICG/WebID/issues/28

**Comment by npm1** [comment]
We have a newer issue about documenting how FedCM should interact with OAuth #599 so I will close this since it captures the request from this issue.
