### ISSUE TITLE
Disallow multiple get() calls at the same time

### ISSUE THREAD

**Issue by npm1** [w3c-fedid/FedCM#340]
The implementation currently will fail your `get()` call if there is another pending call. This is easier to handle in Credentials Management because the algorithms here are ran in parallel, so we cannot keep track of per-document state. Should be fixed with https://github.com/w3c/webappsec-credential-management/issues/206

**Comment by cbiesinger** [comment]
I believe this was fixed by https://github.com/w3c/webappsec-credential-management/pull/207
