### ISSUE TITLE
Multiple IDP support requires patching the HTML spec

### ISSUE THREAD

**Issue by npm1** [w3c-fedid/FedCM#440]
For multi IDP support, we probably want to add an algorithm invocation as mentioned in https://github.com/whatwg/html/pull/8382#issuecomment-1279929852. For now we can monkeypatch the HTML spec but the invocation should move to that spec later.

**Comment by cbiesinger** [comment]
Since we are no longer pursuing coalescing multiple fedcm requests for the multi IDP case, we can close this.

If we decide to restart work on that we can reopen this.
