### ISSUE TITLE
Consider lifting IdentityCredential out of FedCM spec

### ISSUE THREAD

**Issue by RByers** [w3c-fedid/FedCM#457]
As we discuss APIs for other types of identity (like [mdoc](https://github.com/WICG/mobile-document-request-api/pull/5)), there's an idea brewing that `IdentityCredential` shouldn't be FedCM-specific, but should instead be lifted out into another spec somewhere on which FedCM (and others) build. In particular, we imagine scenarios where a site might want identity information from federated IDPs and/or from wallet apps on the system.

How do folks here feel about this idea? To what extent do you feel there's room for breaking changes if it's helpful to make the API more generic? @samuelgoto

**Comment by cbiesinger** [comment]
see also https://github.com/agl/identity-credential

**Comment by RByers** [comment]
Yep, I'm working on getting that proposal ready to share more broadly. 😁

**Comment by siverfishrnup** [comment]
No I'm all for idme

**Comment by mknowles36** [comment]
This now resolved with the introduction of the Digital Credentials API (https://wicg.github.io/digital-credentials) (https://github.com/WICG/digital-credentials/blob/main/explainer.md)
