### ISSUE TITLE
Should getUserInfo() be under IdentityProvider?

### ISSUE THREAD

**Issue by npm1** [w3c-fedid/FedCM#476]
Per https://github.com/fedidcg/FedCM/pull/470 review, it is awkward to have `getUserInfo()` hang off of `IdentityProvider`. However, we currently do not really have any better ideas. While we are for now keeping it there, filing this issue to keep this open for the next few months, while it is still easy to move it around, in case we find a better home for it.

**Comment by samuelgoto** [comment]
The other options we considered was hanging it on `IdentityCredential` as a static method, but (a) there are [more methods](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/credentialmanagement/identity_provider.idl;l=1?q=identity_provider.idl&sq=&ss=chromium) that we'd need to find a better home to and (b) it may not fit well with [this](https://github.com/agl/identity-credential) design too. 

There are a few moving parts here ([example](https://github.com/privacycg/is-logged-in/issues/53)), but I agree that `IdentityProvider.getUserInfo()` is awkward.

We are committed to moving this to a better place if we can find one while FedCM is still in its early days of adoption (say, in the next 6-12 months it should be easy to move it to another object if we find one).
