### ISSUE TITLE
Explainer is out of date. Should we remove it?

### ISSUE THREAD

**Issue by samuelgoto** [w3c-fedid/FedCM#622]
We wrote a series of explainers over the years, but most of them are fairly out of date at this point, as @yoavweiss noted here https://github.com/fedidcg/FedCM/issues/621#issuecomment-2206130679.

The [spec](https://fedidcg.github.io/FedCM) is certainly up to date with Chrome's implementation, but it is probably harder to read than what we'd want to point developers too.

Chrome's [developer documentation](https://developers.google.com/privacy-sandbox/3pcd/fedcm-developer-guide) is also up to date, but we probably want something Chrome-agnostic.

MDN's [developer documentation](https://developer.mozilla.org/en-US/docs/Web/API/FedCM_API) is chrome-agnostic, but not as up to date as Chrome's.

We should probably remove the explainer (or at least mark it as out of date), but that leaves us the question: where should we point developers to?

**Comment by samuelgoto** [comment]
> MDN is pretty good for more settled pieces

Yeah, I'm wondering if we should invest more into making the MDN article really good.

**Comment by aaronpk** [comment]
The MDN article was the most helpful thing I found when i was spinning up on this. Seems like a good resource to continue to maintain.
