### ISSUE TITLE
PP/TOS requirements are different from auto reauthentication

### ISSUE THREAD

**Issue by npm1** [w3c-fedid/FedCM#626]
Currently the spec makes it sound like these two are the same, but they are not. PP/TOS may not be shown if the IdP requests it, whereas auto reauthentication may only occur if the browser knows that this account was previously used.

**Comment by appfon** [comment]
![17255787963628084469761987051968](https://github.com/user-attachments/assets/9f01878c-dd88-44e7-8751-355051d77903)
