### ISSUE TITLE
Break the Login Status API spec out of the FedCM spec 

### ISSUE THREAD

**Issue by samuelgoto** [w3c-fedid/FedCM#641]
Currently, the [Login Status API](https://w3c-fedid.github.io/FedCM/#browser-api-login-status) is bundled inside a section of the FedCM spec, but that's entirely unnecessary: a browser vendor may choose to implement the former but not the latter (but not the other way around).

We should create a spec for the Login Status API that's separate from the FedCM spec so that they can move and be implemented independently.

**Comment by npm1** [comment]
This is not done yet.

**Comment by samuelgoto** [comment]
I think this is now done, with the Login Status API published in its own repo here:

https://w3c-fedid.github.io/login-status/

and removed from the FedCM repo altogether.
