### ISSUE TITLE
PR Preview broke

### ISSUE THREAD

**Issue by npm1** [w3c-fedid/FedCM#643]
It stopped working when we moved the repo presumably.

**Comment by wseltzer** [comment]
It now seems to be working again. Can you double-check?

**Comment by wseltzer** [comment]
or is that only for older PRs. Looking into it further

**Comment by wseltzer** [comment]
Thanks to @simoneonofri we have now actually fixed the issue by installing pr-preview in this org.

**Comment by npm1** [comment]
Thank you :)

**Comment by simoneonofri** [comment]
to leave for posterity, you need to install this in the orga https://github.com/apps/pr-preview (and thanks to denis for the solution)
