### ISSUE TITLE
did think and communicate

### ISSUE THREAD

**Issue by Smy0521** [w3c-fedid/FedCM#649]
Hi, during the research on did decentralization, I found that there are certain limitations in the interoperability and connectivity of did-core (methed).
Because I am currently engaged in digital trust-related work, I have the following thoughts. 
  1. How to communicate with did in different blockchains and under different ledgers.
  2. Whether did can be authenticated by configuring idp and sp like federated authentication.
  3. Is it possible to conduct discussion groups?

嗨 在调研 did 去中心化中发现，针对 did-core （methed）互通性 连通性 有一定局限性，
因为目前从事数字信任相关工作，因此进行以下思考。 
  1、 did 如何在不同区块链中，不同账本下进行互通。
  2、 did 是否能像联邦认证一样，通过配置 idp 及 sp 的方式进行认证。
  3、 是否可以进行讨论组讨论。

**Comment by Smy0521** [comment]
![img_v3_02ej_6b602772-5e4d-4f5e-a2a2-e34285cfd29g](https://github.com/user-attachments/assets/d1cd8b6c-46df-4811-84b4-d904a311c14b)

**Comment by npm1** [comment]
Seems to be filed in the wrong repository? Closing

**Comment by Smy0521** [comment]
> Seems to be filed in the wrong repository? Closing

why？

**Comment by npm1** [comment]
It is not clear at all how your issue is related to FedCM. Perhaps I am unfamiliar with a lot of the terminology you are using but I also asked teammates and they did not understand either. You'll have to expand and explain a bit more what this issue is about and how it is related to the FedCM API.

**Comment by timcappalli** [comment]
I agree. This is unrelated to FedCM and should be closed.
