### ISSUE TITLE
login fencedframes: exfiltration through show/hide signal?

### ISSUE THREAD

**Issue by jeremyroman** [w3c-fedid/FedCM#65]
In the example with fenced frames and permissions, it appears that before user interaction the IDP frame has some mechanism to communicate 1 bit of information indicating whether the frame should be shown or not (presumably the IDP popup needs to be hidden by the RP if no account is available).

Since these frames have access to first-party cookies, it seems that the RP in cooperation with a tracking "IDP" could do this:

```
<fencedframe src="//tracker.example/0.wbn"></fencedframe>
<fencedframe src="//tracker.example/1.wbn"></fencedframe>
...
<fencedframe src="//tracker.example/63.wbn"></fencedframe>
```

and then use the show/hide signal on each to extract 1 bit of information, extended in this way to an arbitrarily large identifier without user interaction.

Even if this is limited to one per origin, using same-site origins (which can share site cookies) or a sufficient set of coordinating domains could potentially create a unique trackable identifier.

**Comment by npm1** [comment]
FedCM does not work in FencedFrames and it is unclear how this issue is related to FedCM. So closing but feel free to comment if you feel something is missing.

**Comment by jeremyroman** [comment]
Well, I don't remember precisely what the explainer said 3.5 years ago. I think a previous proposal involved sign-in buttons for IDPs being embedded as a kind of fenced frame -- which may no longer exist in modern FedCM.
